/*
 * Cool Gallery  v1.0.1.4
 *
 * Copyright 2018-2021, LambertGroup
 *
 */

 var gallery1_api_videoImages=[];
 (function(e){function p(a){var b="cubic-bezier(0.250, 0.250, 0.750, 0.750)";switch(a){case "linear":b="cubic-bezier(0.250, 0.250, 0.750, 0.750)";break;case "swing":b="cubic-bezier(0.250, 0.100, 0.250, 1.000)";break;case "ease":b="cubic-bezier(0.250, 0.100, 0.250, 1.000)";break;case "ease-in":b="cubic-bezier(0.420, 0.000, 1.000, 1.000)";break;case "ease-out":b="cubic-bezier(0.000, 0.000, 0.580, 1.000)";break;case "ease-in-out":b="cubic-bezier(0.420, 0.000, 0.580, 1.000)";break;case "easeInQuad":b=
 "cubic-bezier(0.550, 0.085, 0.680, 0.530)";break;case "easeOutQuad":b="cubic-bezier(0.250, 0.460, 0.450, 0.940)";break;case "easeInOutQuad":case "easeInCubic":b="cubic-bezier(0.550, 0.055, 0.675, 0.190)";break;case "easeOutCubic":b="cubic-bezier(0.215, 0.610, 0.355, 1.000)";break;case "easeInOutCubic":b="cubic-bezier(0.645, 0.045, 0.355, 1.000)";break;case "easeInQuart":b="cubic-bezier(0.895, 0.030, 0.685, 0.220)";break;case "easeOutQuart":b="cubic-bezier(0.165, 0.840, 0.440, 1.000)";break;case "easeInOutQuart":b=
 "cubic-bezier(0.770, 0.000, 0.175, 1.000)";break;case "easeInQuint":b="cubic-bezier(0.755, 0.050, 0.855, 0.060)";break;case "easeOutQuint":b="cubic-bezier(0.230, 1.000, 0.320, 1.000)";break;case "easeInOutQuint":b="cubic-bezier(0.860, 0.000, 0.070, 1.000)";break;case "easeInSine":b="cubic-bezier(0.470, 0.000, 0.745, 0.715)";break;case "easeOutSine":b="cubic-bezier(0.390, 0.575, 0.565, 1.000)";break;case "easeInOutSine":b="cubic-bezier(0.445, 0.050, 0.550, 0.950)";break;case "easeInExpo":b="cubic-bezier(0.950, 0.050, 0.795, 0.035)";
 break;case "easeOutExpo":b="cubic-bezier(0.190, 1.000, 0.220, 1.000)";break;case "easeInOutExpo":b="cubic-bezier(1.000, 0.000, 0.000, 1.000)";break;case "easeInCirc":b="cubic-bezier(0.600, 0.040, 0.980, 0.335)";break;case "easeOutCirc":b="cubic-bezier(0.075, 0.820, 0.165, 1.000)";break;case "easeInOutCirc":b="cubic-bezier(0.785, 0.135, 0.150, 0.860)";break;case "easeInBack":b="cubic-bezier(0.600, -0.280, 0.735, 0.045)";break;case "easeOutBack":b="cubic-bezier(0.175, 0.885, 0.320, 1.275)";break;case "easeInOutBack":b=
 "cubic-bezier(0.680, -0.550, 0.265, 1.550)"}return b}function F(a){var b=!1;a=a.substr(a.length-4).toLowerCase();if(".jpg"==a||".png"==a||".gif"==a)b=!0;return b}function G(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}function H(a){return(r=a.match(/^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i))?r.slice(1,4).map(function(a){return parseInt(a,16)}):(r=a.match(/^#([0-9a-f])([0-9a-f])([0-9a-f])$/i))?
 r.slice(1,4).map(function(a){return 17*parseInt(a,16)}):null}function q(a,b){var e=parseInt(b/a.columns,10)+1;0===b%a.columns&&e--;return e}function t(a,b){parseInt(b/a.columns,10);var e=b%a.columns;0===e&&(e=a.columns);return e}function n(a,b,e,d,c,g){e>=c&&d>=g&&(e=e*g/d,d=g);e<=c&&(d=d*c/e,e=c);d<=g&&(e=e*g/d,d=g);return parseInt(e+4,10)+"px "+parseInt(d+4,10)+"px"}function C(a,b,h,d,c,g,m,f){e("#itemHolderUnit"+a.my_rand+"_"+f).css({left:g+"px",top:m+"px"});e("#itemHolderUnit"+a.my_rand+"_"+f).css({width:d+
 "px",height:c+"px","-webkit-background-size":n(a,b,a.currentImgWidth[f],a.currentImgHeight[f],d,c),"-moz-background-size":n(a,b,a.currentImgWidth[f],a.currentImgHeight[f],d,c),"-ms-background-size":n(a,b,a.currentImgWidth[f],a.currentImgHeight[f],d,c),"-o-background-size":n(a,b,a.currentImgWidth[f],a.currentImgHeight[f],d,c),"background-size":n(a,b,a.currentImgWidth[f],a.currentImgHeight[f],d,c),"-webkit-transition-duration":b.zoomDuration+"s","-moz-transition-duration":b.zoomDuration+"s","-ms-transition-duration":b.zoomDuration+
 "s","-o-transition-duration":b.zoomDuration+"s","transition-duration":b.zoomDuration+"s","-webkit-transition-timing-function":p(b.zoomEffect),"-moz-transition-timing-function":p(b.zoomEffect),"-ms-transition-timing-function":p(b.zoomEffect),"-o-transition-timing-function":p(b.zoomEffect),"transition-timing-function":p(b.zoomEffect),"-webkit-transition-delay":a.zoom_delay+"s","-moz-transition-delay":a.zoom_delay+"s","-ms-transition-delay":a.zoom_delay+"s","-o-transition-delay":a.zoom_delay+"s","transition-delay":a.zoom_delay+
 "s",perspective:"0","-webkit-perspective":"0"})}function D(a,b,h){b=1;h=!0;do{if(4<=Math.abs(e("#itemHolderUnit"+a.my_rand+"_"+b).width()-a.itemWidth)||4<=Math.abs(e("#itemHolderUnit"+a.my_rand+"_"+b).height()-a.itemHeight))h=!1;b++}while(b<a.rows*a.columns&&h);return h}function B(a,b,h,d){var c=b.galleryBg,g=a.itemWidth,m=a.itemHeight,f=g+"px "+m+"px",z=q(a,d),A=t(a,d);itemHolderUnit=e('<div class="itemHolderUnit" rel="'+d+'" id="itemHolderUnit'+a.my_rand+"_"+d+'"><div class="img_icon"></div><div class="img_desc"><div class="img_desc_padding"><strong>'+
 a.currentTitle[d]+"</strong><br>"+a.currentDescription[d]+"</div></div></div>");h.append(itemHolderUnit);c=d<=a.total_images?"url("+a.currentImg[d].attr("src")+")":"#FFF000";0<a.currentImgOrigWidth[d]&&(g=a.currentImgOrigWidth[d]);0<a.currentImgOrigHeight[d]&&(m=a.currentImgOrigHeight[d]);a.currentImgWidth[d]=g;a.currentImgHeight[d]=m;if(g!=a.itemWidth||m!=a.itemHeight)f=n(a,b,g,m,a.itemWidth,a.itemHeight);itemHolderUnit.css({width:a.itemWidth+"px",height:a.itemHeight+"px","background-image":c,"background-position":a.currentbgHorizontalPosition[d]+
 " "+a.currentbgVerticalPosition[d],"background-repeat":"no-repeat","-webkit-background-size":f,"-moz-background-size":f,"-ms-background-size":f,"-o-background-size":f,"background-size":f,display:"block",left:a.itemWidth*(A-1)+b.gutter*A+"px",top:a.itemHeight*(z-1)+b.gutter*z+"px","-webkit-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset","-moz-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset","-ms-box-shadow":"0px 0px 0px "+b.itemBorderWidth+
 "px "+b.itemBorderColorOFF+" inset","-o-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset","box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset","-webkit-box-sizing":"border-box","-moz-box-sizing":"border-box","-ms-box-sizing":"border-box","-o-box-sizing":"border-box","box-sizing":"border-box"});b.showImageDescription&&e(".img_desc",h).css({"background-color":"rgba("+H(b.imageDescriptionBgColor)+","+b.imageDescriptionBgOpacity/100+")",color:b.imageDescriptionTextColor});
 void 0!=a.currentLightbox[d]&&""!=a.currentLightbox[d]?itemHolderUnit.wrap('<a href="'+a.currentLightbox[d]+'" rel="lightBoxLBG'+a.thisGelleryId+'[lbg_pp_gal]"></a>'):void 0!=a.currentLink[d]&&""!=a.currentLink[d]&&(c=b.target,void 0!=a.currentTarget[d]&&""!=a.currentTarget[d]&&(c=a.currentTarget[d]),itemHolderUnit.wrap('<a href="'+a.currentLink[d]+'" target="'+c+'"></a>'));e("#itemHolderUnit"+a.my_rand+"_"+d).on("mouseover",function(){(""!=a.currentTitle[d]&&void 0!=a.currentTitle[d]||""!=a.currentDescription[d]&&
 void 0!=a.currentDescription[d])&&b.showImageDescription&&(e(this).parent().attr("org_title",e(this).parent().attr("title")),e(this).parent().attr("title",""),e(".img_desc",this).css({opacity:1,"-webkit-transition-duration":b.zoomDuration+"s","-moz-transition-duration":b.zoomDuration+"s","-ms-transition-duration":b.zoomDuration+"s","-o-transition-duration":b.zoomDuration+"s","transition-duration":b.zoomDuration+"s"}));if(void 0!=a.currentLightbox[d]&&""!=a.currentLightbox[d]&&b.showIconOverImage){var c=
 a.currentLightbox[d];-1!=c.indexOf("youtube.com/")||-1!=c.indexOf("vimeo.com/")?e(".img_icon",this).addClass("video_icon"):e(".img_icon",this).addClass("lightbox_icon");e(".img_icon",this).css({opacity:1,"-webkit-transition-duration":b.zoomDuration+"s","-moz-transition-duration":b.zoomDuration+"s","-ms-transition-duration":b.zoomDuration+"s","-o-transition-duration":b.zoomDuration+"s","transition-duration":b.zoomDuration+"s"})}void 0!=a.currentLink[d]&&""!=a.currentLink[d]&&b.showIconOverImage&&(e(".img_icon",
 this).addClass("link_icon"),e(".img_icon",this).css({opacity:1,"-webkit-transition-duration":b.zoomDuration+"s","-moz-transition-duration":b.zoomDuration+"s","-ms-transition-duration":b.zoomDuration+"s","-o-transition-duration":b.zoomDuration+"s","transition-duration":b.zoomDuration+"s"}));if(!a.please_wait){D(a,b,h)&&(a.please_wait=!0,clearTimeout(a.please_wait_interval),a.please_wait_interval=setTimeout(function(){a.please_wait=!1},1E3*b.zoomDuration));var f=c=0,u=0,v=0,z=0,A=0,n=0,p=0,k=1,l=1;
 0<b.itemBorderWidth&&e("#itemHolderUnit"+a.my_rand+"_"+d).css({"-webkit-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorON+" inset","-moz-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorON+" inset","-ms-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorON+" inset","-o-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorON+" inset","box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorON+" inset"});f=Math.max(a.rows-
 1,1)*a.itemHeight+Math.max(a.rows-1,1)*b.gutter;c=f*g/m;c>=.7*(a.width-(a.columns+1)*b.gutter)&&(c=.7*(a.width-(a.columns+1)*b.gutter),f=c*m/g);2>=a.columns&&(c=.85*a.width,f=c*m/g);z=(a.width-c-(a.columns+1)*b.gutter)/(a.columns-1);A=(a.height-f-(a.rows+1)*b.gutter)/(a.rows-1);u=(a.width-c-(a.columns+1)*b.gutter)/(a.columns-1);v=(a.height-f-(a.rows+1)*b.gutter)/(a.rows-1);for(var w=1;w<=a.rows*a.columns;w++){k=q(a,w);l=t(a,w);var x=a.itemWidth*(l-1)+b.gutter*l;var y=a.itemHeight*(k-1)+b.gutter*k+
 500;w!=d?(k==q(a,d)&&(x=l<t(a,d)?u*Math.max(l-1,0)+b.gutter*l:u*Math.max(l-2,0)+b.gutter*l+c,y=v*Math.max(k-1,0)+b.gutter*k,n=z,p=f),l==t(a,d)&&(y=k<q(a,d)?v*Math.max(k-1,0)+b.gutter*k:v*Math.max(k-2,0)+b.gutter*k+f,x=u*Math.max(l-1,0)+b.gutter*l,n=c,p=A),k!=q(a,d)&&l!=t(a,d)&&(y=k<q(a,d)?v*Math.max(k-1,0)+b.gutter*k:v*Math.max(k-2,0)+b.gutter*k+f,x=l<t(a,d)?u*Math.max(l-1,0)+b.gutter*l:u*Math.max(l-2,0)+b.gutter*l+c,n=u,p=v),C(a,b,h,n,p,x,y,w)):(k=q(a,d),l=t(a,d),x=u*Math.max(l-1,0)+b.gutter*l,y=
 v*Math.max(k-1,0)+b.gutter*k,C(a,b,h,c,f,x,y,d))}}});e("#itemHolderUnit"+a.my_rand+"_"+d).on("mouseout",function(){a.click_arr[d]=0;(""!=a.currentTitle[d]&&void 0!=a.currentTitle[d]||""!=a.currentDescription[d]&&void 0!=a.currentDescription[d])&&b.showImageDescription&&(e(this).parent().attr("title",e(this).parent().attr("org_title")),e(".img_desc",this).css({opacity:0,"-webkit-transition-duration":b.zoomDuration+"s","-moz-transition-duration":b.zoomDuration+"s","-ms-transition-duration":b.zoomDuration+
 "s","-o-transition-duration":b.zoomDuration+"s","transition-duration":b.zoomDuration+"s"}));void 0!=a.currentLightbox[d]&&""!=a.currentLightbox[d]&&b.showIconOverImage&&(e(".img_icon",this).removeClass("lightbox_icon"),e(".img_icon",this).css({opacity:0,"-webkit-transition-duration":b.zoomDuration+"s","-moz-transition-duration":b.zoomDuration+"s","-ms-transition-duration":b.zoomDuration+"s","-o-transition-duration":b.zoomDuration+"s","transition-duration":b.zoomDuration+"s"}));void 0!=a.currentLink[d]&&
 ""!=a.currentLink[d]&&b.showIconOverImage&&(e(".img_icon",this).removeClass("link_icon"),e(".img_icon",this).css({opacity:0,"-webkit-transition-duration":b.zoomDuration+"s","-moz-transition-duration":b.zoomDuration+"s","-ms-transition-duration":b.zoomDuration+"s","-o-transition-duration":b.zoomDuration+"s","transition-duration":b.zoomDuration+"s"}));if("itemHolderUnit"==e(this).attr("class")&&!a.please_wait){q(a,d);t(a,d);0<b.itemBorderWidth&&e("#itemHolderUnit"+a.my_rand+"_"+d).css({"-webkit-box-shadow":"0px 0px 0px "+
 b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset","-moz-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset","-ms-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset","-o-box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset","box-shadow":"0px 0px 0px "+b.itemBorderWidth+"px "+b.itemBorderColorOFF+" inset"});for(var c=1;c<=a.rows*a.columns;c++){var f=q(a,c);var m=t(a,c);m=a.itemWidth*(m-1)+b.gutter*m;f=a.itemHeight*
 (f-1)+b.gutter*f;C(a,b,h,a.itemWidth,a.itemHeight,m,f,c)}}});e("#itemHolderUnit"+a.my_rand+"_"+d).parent().on("click",function(c){c.stopPropagation();if(void 0!=e(this).attr("href")&&""!=e(this).attr("href")){(""!=a.currentTitle[d]&&void 0!=a.currentTitle[d]||""!=a.currentDescription[d]&&void 0!=a.currentDescription[d])&&e(this).parent().attr("title",e(this).parent().attr("org_title"));if(-1!=a.userAgentVal.indexOf("android")||-1!=a.userAgentVal.indexOf("ipad")||-1!=a.userAgentVal.indexOf("iphone")||
 -1!=a.userAgentVal.indexOf("ipod")||-1!=a.userAgentVal.indexOf("webos")){if(c.preventDefault(),void 0!=a.click_arr[d]?a.click_arr[d]++:a.click_arr[d]=1,void 0!=a.currentLink[d]&&""!=a.currentLink[d]&&1<a.click_arr[d]){var f=b.target;void 0!=a.currentTarget[d]&&""!=a.currentTarget[d]&&(f=a.currentTarget[d]);window.open(a.currentLink[d],f)}}else a.click_arr[d]=2;void 0!=a.currentLightbox[d]&&""!=a.currentLightbox[d]&&(c.preventDefault(),1<a.click_arr[d]&&(e.prettyPhotoFamous.open(a.api_images,a.api_i,
 a.api_titles),e.prettyPhotoFamous.changePage(a.api_i.indexOf(d)),location.hash="lightBoxLBG"+a.thisGelleryId+"[lbg_pp_gal]/"+a.api_i.indexOf(d)+"/"))}})}function E(a,b,h){var d=!1;responsiveWidth=h.parent().width();b.width100Proc?d=!0:responsiveWidth!=a.width&&(responsiveWidth<=b.width||(responsiveWidth=b.width),d=!0);if(d){h.empty();a.width=responsiveWidth;a.columns=b.columns;a.rows=b.rows;a.itemWidth=(a.width-(a.columns+1)*b.gutter)/a.columns;a.itemHeight=(b.height-(a.rows+1)*b.gutter)/a.rows;if(130>=
 a.itemWidth){d=!1;do--a.columns,a.rows=Math.ceil(b.rows*b.columns/a.columns),a.itemWidth=(a.width-(a.columns+1)*b.gutter)/a.columns,a.itemHeight=parseInt(a.itemWidth*a.orig_itemHeight/a.orig_itemWidth,10),130<a.itemWidth&&(d=!0);while(!1===d)}a.itemWidth=parseInt(a.itemWidth,10);a.itemHeight=parseInt(a.itemHeight,10);a.width=a.itemWidth*a.columns+b.gutter*(a.columns+1);a.height=a.itemHeight*a.rows+b.gutter*(a.rows+1);h.css({width:a.width+"px",height:a.height+"px"});for(i=1;i<=a.total_images;i++)a.click_arr[i]=
 0,B(a,b,h,i);if(a.rows*a.columns>a.total_images)for(d=1;d<=a.rows*a.columns-a.total_images;d++)a.click_arr[a.total_images+d]=0,a.currentImgOrigWidth[a.total_images+d]=490,a.currentImgOrigHeight[a.total_images+d]=350,B(a,b,h,a.total_images+d);e("a[rel^='no_relation']").prettyPhotoFamous({show_title:!1,theme:"dark_rounded",deeplinking:!0,social_tools:""})}}e.gallery1={version:"1.0"};e.fn.gallery1=function(a){a=e.extend({},e.fn.gallery1.defaults,a);return this.each(function(){var b=e(this),h=e("<div></div>").addClass("gallery1").addClass(a.type);
 b.wrap(h);var d=b.parent(".gallery1");a.width100Proc&&(a.width=d.parent().width());a.height100Proc&&0<d.parent().height()&&(a.height=d.parent().height());a.centerGallery&&d.css({margin:"0 auto"});1>a.gutter&&(a.gutter=1);d.on("mouseout",function(b){for(b=b.relatedTarget;null!=b;){if(b==this)return;b=b.parentNode}c.please_wait=!0;clearTimeout(c.please_wait_interval);c.please_wait_interval=setTimeout(function(){c.please_wait=!1},1E3*a.zoomDuration);D(c,a,d)&&(c.please_wait=!1,clearTimeout(c.please_wait_interval))});
 var c={total_images:0,width:a.width,height:a.height,itemWidth:0,itemHeight:0,orig_itemWidth:0,orig_itemHeight:0,rows:a.rows,columns:a.columns,currentLi:"",currentImg:[],currentImgWidth:[],currentImgHeight:[],currentImgOrigWidth:[],currentImgOrigHeight:[],currentLightbox:[],currentTitle:[],currentDescription:[],currentLink:[],currentTarget:[],currentbgHorizontalPosition:[],currentbgVerticalPosition:[],api_images:[],api_titles:[],api_i:[],bg_aux:a.galleryBg,windowWidth:0,please_wait:!1,please_wait_interval:0,
 zoom_delay:0,zoom_delay_interval:0,click_arr:[],userAgentVal:String(navigator.userAgent).toLowerCase(),my_rand:Math.floor(1E7*Math.random()),thisGelleryId:e(this).attr("id")};F(a.galleryBg)&&(c.bg_aux="url("+a.galleryBg+")");c.itemWidth=(c.width-(c.columns+1)*a.gutter)/c.columns;c.itemHeight=(c.height-(c.rows+1)*a.gutter)/c.rows;c.itemWidth=parseInt(c.itemWidth,10);c.itemHeight=parseInt(c.itemHeight,10);c.orig_itemWidth=(a.width-(c.columns+1)*a.gutter)/c.columns;c.orig_itemHeight=(a.height-(c.rows+
 1)*a.gutter)/c.rows;c.width=c.itemWidth*c.columns+a.gutter*(c.columns+1);c.height=c.itemHeight*c.rows+a.gutter*(c.rows+1);d.css({width:c.width+"px",height:c.height+"px",background:c.bg_aux});b=b.find("ul:first").children();c.total_images=0;c.currentLightbox[0]="";c.currentTitle[0]="";c.currentDescription[0]="";c.currentbgHorizontalPosition[0]="";c.currentbgVerticalPosition[0]="";b.each(function(){c.currentLi=e(this);c.currentLi.is("li")||(c.currentLi=c.currentLi.find("li:first"));c.currentLi.is("li")&&
 (c.total_images++,c.currentLink[c.total_images]="",c.currentTarget[c.total_images]=a.target,c.currentLightbox[c.total_images]="",c.currentTitle[c.total_images]="",c.currentDescription[c.total_images]="",void 0!=c.currentLi.attr("data-link")&&""!=c.currentLi.attr("data-link")&&(c.currentLink[c.total_images]=c.currentLi.attr("data-link"),void 0!=c.currentLi.attr("data-target")&&""!=c.currentLi.attr("data-target")&&(c.currentTarget[c.total_images]=c.currentLi.attr("data-target"))),void 0!=c.currentLi.attr("data-lightbox")&&
 ""!=c.currentLi.attr("data-lightbox")&&(c.currentLightbox[c.total_images]=c.currentLi.attr("data-lightbox")),void 0!=c.currentLi.attr("data-title")&&""!=c.currentLi.attr("data-title")&&(c.currentTitle[c.total_images]=c.currentLi.attr("data-title")),void 0!=c.currentLi.attr("data-description")&&""!=c.currentLi.attr("data-description")&&(c.currentDescription[c.total_images]=c.currentLi.attr("data-description")),void 0!=c.currentLi.attr("data-horizontal")&&""!=c.currentLi.attr("data-horizontal")?c.currentbgHorizontalPosition[c.total_images]=
 c.currentLi.attr("data-horizontal"):c.currentbgHorizontalPosition[c.total_images]=a.bgHorizontalPosition,void 0!=c.currentLi.attr("data-vertical")&&""!=c.currentLi.attr("data-vertical")?c.currentbgVerticalPosition[c.total_images]=c.currentLi.attr("data-vertical"):c.currentbgVerticalPosition[c.total_images]=a.bgVerticalPosition,c.currentImg[c.total_images]=c.currentLi.find("img:first"),0<e(c.currentImg[c.total_images]).width()&&(c.currentImgOrigWidth[c.total_images]=e(c.currentImg[c.total_images]).width()),
 0<e(c.currentImg[c.total_images]).height()&&(c.currentImgOrigHeight[c.total_images]=e(c.currentImg[c.total_images]).height()),B(c,a,d,c.total_images))});b=-1;for(i=1;i<=c.total_images;i++)if(void 0!=c.currentLightbox[i]&&""!=c.currentLightbox[i]){b++;c.api_images[b]=c.currentLightbox[i];lightbox_string=c.currentLightbox[i];if(-1!=lightbox_string.indexOf("youtube.com/")||-1!=lightbox_string.indexOf("vimeo.com/"))gallery1_api_videoImages[lightbox_string]=c.currentImg[i].attr("src");c.api_titles[b]=
 "<strong>"+c.currentTitle[i]+"</strong><br>"+c.currentDescription[i];c.api_i[b]=i}e.gallery1.getVideoImageForShare=function(a){return gallery1_api_videoImages[a]};if(c.rows*c.columns>c.total_images)for(b=1;b<=c.rows*c.columns-c.total_images;b++)c.currentImgOrigWidth[c.total_images+b]=490,c.currentImgOrigHeight[c.total_images+b]=350,B(c,a,d,c.total_images+b);e("a[rel^='no_relation']").prettyPhotoFamous({show_title:!1,theme:"dark_rounded",deeplinking:!0,social_tools:""});window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,
 version:"v3.1",status:!0,cookie:!0,xfbml:!0})};(function(a,b,c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//connect.facebook.com/en_US/sdk.js",d.parentNode.insertBefore(a,d))})(document,"script","facebook-jssdk");e.gallery1.shareOverrideOGMeta=function(a,b,c,d){FB.ui({method:"share_open_graph",action_type:"og.likes",action_properties:JSON.stringify({object:{"og:url":decodeURI(a).replace("%23","#"),"og:title":b,"og:description":c,"og:image":d}})},function(a){})};
 E(c,a,d);var g=!1;e(window).resize(function(){var b=G();doResizeNow=!0;-1!=b&&9==b&&0==c.windowWidth&&(doResizeNow=!1);c.windowWidth==e(window).width()?(doResizeNow=!1,a.windowCurOrientation==window.orientation||-1==c.userAgentVal.indexOf("android")&&-1==c.userAgentVal.indexOf("ipad")&&-1==c.userAgentVal.indexOf("iphone")&&-1==c.userAgentVal.indexOf("ipod")&&-1==c.userAgentVal.indexOf("webos")||(a.windowCurOrientation=window.orientation,doResizeNow=!0)):c.windowWidth=e(window).width();doResizeNow&&
 (!1!==g&&clearTimeout(g),g=setTimeout(function(){E(c,a,d)},200))})})};e.fn.gallery1.defaults={width:1E3,height:600,width100Proc:!1,height100Proc:!1,rows:3,columns:5,centerGallery:!0,total_images:0,gutter:2,galleryBg:"#222222",itemBorderWidth:0,itemBorderColorOFF:"transparent",itemBorderColorON:"#FF0000",showImageDescription:!0,imageDescriptionBgColor:"#000000",imageDescriptionBgOpacity:30,imageDescriptionTextColor:"#FFFFFF",showIconOverImage:!0,zoomDuration:1,zoomEffect:"linear",target:"_blank",bgHorizontalPosition:"center",
 bgVerticalPosition:"center",facebookAppID:"",windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
